export enum ActionTypes {
    LOADING = "LOADING",
    CLEAR_NAME = "CLEAR_NAME",
    SAVE_NAME = "SAVE_NAME",
    INIT = "INIT",
    IS_LOGGING_OUT = "IS_LOGGING_OUT",
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT",
    GAME_START = "GAME_START",
    GAME_END = "GAME_END",
    GAME_RESET = "GAME_RESET",
    GAME_JUMP = "GAME_JUMP",
    GAME_CLICK = "GAME_CLICK",
}
